### ISSUE TITLE
blender4.3版本会将蜡笔修改器屏蔽掉

### ISSUE THREAD

**Issue by NewTypo** [Dangry98/modifier_list-for-Blender-4.0#10]
![blender_8mo9Gk5GTO](https://github.com/user-attachments/assets/a92ec475-a2ef-4ea8-aa65-ad91e562e7df)
如上图所示

**Comment by Dangry98** [comment]
same as https://github.com/Dangry98/modifier_list-for-Blender-4.0/issues/11, closing duplicate report
