### ISSUE TITLE
On grease pencil object "add modifier" button disappears

### ISSUE THREAD

**Issue by Meitt** [Dangry98/modifier_list-for-Blender-4.0#11]
On blender 4.3 when I try add modifier on grease pencil object there is not a button "add modifier" in modifiers tabs. Once i deactivate addon, the button appears.
![image](https://github.com/user-attachments/assets/2e09c274-14d7-4fc3-84b2-f24d9ef87928)
![image](https://github.com/user-attachments/assets/779f0eac-a700-4fcf-9828-93adacb5702e)

**Comment by Dangry98** [comment]
Thanks for the report! I have no idea what could cases this, so I need to investigate.

**Comment by Dangry98** [comment]
In 4.2 the modifier tab was split into:
DATA_PT_modifiers_pre
DATA_PT_gpencil_modifiers_pre

Now its just DATA_PT_modifiers_pre, this  can not be fixed.

**Comment by Dangry98** [comment]
I made a workaround for this in 1.9.4
