### ISSUE TITLE
Incompatibility of New Version (1.9.35) with blender 4.2.4

### ISSUE THREAD

**Issue by silv3rarr0w** [Dangry98/modifier_list-for-Blender-4.0#13]
This Blender version (4.2.4) doesn't meet the minimum supported version (4.3.0)

![image](https://github.com/user-attachments/assets/ce5c1e78-a282-4b05-97e8-6e48169609dc)

Neither drag and drop to download form extension platform nor install from disk cannot install 1.9.35
Search and download inside blender will install version 1.9.2

**Comment by silv3rarr0w** [comment]
Tried 1.930, same

**Comment by Dangry98** [comment]
1.9.2 is the latest version that works with 4.2

**Comment by Dangry98** [comment]
> > 1.9.2 is the latest version that works with 4.2, installing from within Blender will pick the right version
> 
> Oh I see, it's my bad. Maybe the update both support the latest version and the latest LTS version would be a good idea? I saw some extensions did this before. But if it takes too much time, just forget it, because I'm just an amateur :)

Its 100% possiable to keep supporting both versions at the same time, but to it would take a bit too much of my very limted time, and I see nothing that would stopp 1.9.2 from working in the LTS version. So worst case some people might miss out some newer features in Modifier List, if they keep using 4.2, maybe.
