### ISSUE TITLE
Error when applying modifiers as shape keys (tried lattice and simple deform)

### ISSUE THREAD

**Issue by SvenViland** [Dangry98/modifier_list-for-Blender-4.0#14]
![image](https://github.com/user-attachments/assets/0679f7ce-e393-44ee-93d5-35637fa9b5ef)

Blender 4.3.0

**Comment by Dangry98** [comment]
Thanks for the report! I will look into it when I get time.

**Comment by Dangry98** [comment]
Fixed in 1.9.7

**Comment by SvenViland** [comment]
Thank you
