### ISSUE TITLE
Rename N-Panel Modifier List

### ISSUE THREAD

**Issue by 47b3r70** [Dangry98/modifier_list-for-Blender-4.0#15]
Hi Dan-Gry, Thank you for creating Modifier List [Fork], a Wonderful Addon for Blender. I would like to point out that I found a small, minor bug in Blender 4.3.0.

I renamed the N-Panel item, from Modifier List, to MdList.

The Modifiers and Vertex Groups menus are included in MdList, while for the Attributes menu an additional item labeled as Modifier List is created, instead of MdList.

To fix it I made the change to the sidebar.py file, writing in the following line:

bl_category = "MdList"

instead of Modifier List.

It's not a perfect solution but it works, and now all menus are included in the MdList entry.

I await the next update, and Thank You for the Excellent Work Done.

Alberto

**Comment by Dangry98** [comment]
Thanks for the report! My bad, I did a simple one line mistake. Fixed in 1.9.67
