### ISSUE TITLE
Some icons under the light theme have readability problems.

### ISSUE THREAD

**Issue by silv3rarr0w** [Dangry98/modifier_list-for-Blender-4.0#18]
Visibility, apply, delete, toggle, these icons works well under dark theme, but hard to read under light theme since they dont change color with theme change.
![image](https://github.com/user-attachments/assets/93aef853-65c6-4d25-9bc7-ea6951b00f2a)
![image](https://github.com/user-attachments/assets/b6cd4d08-0ed7-4e80-b6ef-bfc042d5d82f)
blender 4.2.4
modifier list 1.9.72

**Comment by silv3rarr0w** [comment]
![image](https://github.com/user-attachments/assets/67b68681-a911-489d-8698-21e342781079)
icons under deep gray

**Comment by Dangry98** [comment]
Hi, please change the icon colors:
![image](https://github.com/user-attachments/assets/afd3fd9f-6234-4a6b-9a12-c87aff604d54)

**Comment by silv3rarr0w** [comment]
> Hi, please change the icon colors: ![image](https://private-user-images.githubusercontent.com/42185237/399023230-afd3fd9f-6234-4a6b-9a12-c87aff604d54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNTc2MDUsIm5iZiI6MTczNTM1NzMwNSwicGF0aCI6Ii80MjE4NTIzNy8zOTkwMjMyMzAtYWZkM2ZkOWYtNjIzNC00YTZiLTlhMTItYzg3YWZmNjA0ZDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDAzNDE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MTQ0YmE4N2U1ZjNhNjRhMTU5NDFjNzM2ZDgwZjcyNzBlYTlmOThkZDQwODg0NThjOWMyZTJiYmM1YjNiMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9PeaU9naQ8NIkP16VdiWHZT1x-gof4epsi6cUOlyUco)

I use the auto dark mode plugin, which will automatically switch the bright theme to dark at night. This is what bothers me. It will take some time if I change it manually every time. I noticed that the move modifier up/down on the right automatically changes color with the theme change. Are they different?
![image](https://github.com/user-attachments/assets/ed99996a-cde8-4c43-a906-67333e7e7027)
![image](https://github.com/user-attachments/assets/35b845d5-6b5c-4cad-ba5a-4c59d9c1926c)

In addition, after changing the icon color in the plug-in, the above four buttons and two buttons have not changed. I think this is some kind of bug.
![image](https://github.com/user-attachments/assets/e0f2befa-d892-4ba1-a078-dbc65a28d3f4)
![image](https://github.com/user-attachments/assets/966c0ca8-1c2f-4b46-870c-3fe2a6d7bc99)

**Comment by Dangry98** [comment]
> I noticed that the move modifier up/down on the right automatically changes color with the theme change. Are they different?

Yes, they are just deafult Blender buttons.


> I use the auto dark mode plugin, which will automatically switch the bright theme to dark at night. This is what bothers me. It will take some time if I change it manually every time.

You could make change in code in the auto dark mode plugin to support modifier list, and submit a pull request, or contact the author about it. I feel like it would be better if it was fixed directly in the auto dark mode plugin.

**Comment by silv3rarr0w** [comment]
> You could make change in code in the auto dark mode plugin to support modifier list, and submit a pull request, or contact the author about it. I feel like it would be better if it was fixed directly in the auto dark mode plugin.

I don't think changing the code of auto dark mode has fundamentally solved the problem. Perhaps it is a good choice to use the deafult buttons. The modifier tools plugin I have been using before have no similar problems, their icons perform well in both dark and light themes as their icons are build in.

![image](https://github.com/user-attachments/assets/2e12f118-74e6-4b8b-bba4-8a6f9142fb0f)
![image](https://github.com/user-attachments/assets/8b7f7138-c706-422e-8eec-b0f44f303fbc)
