### ISSUE TITLE
Visibility toggles not working

### ISSUE THREAD

**Issue by zerodean** [Dangry98/modifier_list-for-Blender-4.0#19]
_***EDIT: Turns out something was messed up with my install (as you can see from the screenshot). A conflict with another modifier addon, I think. I uninstalled modifier list and reinstalled from scratch and restarted. Seems to work as expected.**_

Blender 4.3.2 stable
Windows 11

Example workflow:

1. Add a ND Primitive Torus
2. Add an edit mesh

The edit mesh turns off the visibility (icon only) for both the Torus and Edit Mesh.
Turning on Edit Mesh visibility has no effect
Turning on Torus visibility (already visible) turns off an Edit Mesh (if mesh is modified)
Deleting the edit mesh modifier has no effect (it retains the edited mesh) -- but apparently that's because the visibility of the torus is toggled to off. Very confusing.

![image](https://github.com/user-attachments/assets/1f8b1c58-aa78-426c-86a9-a5e3c62a316c)

**Comment by Dangry98** [comment]
Hi Zerodean, you might have accidentally switched over to stack mode in modifier list.
![image](https://github.com/user-attachments/assets/f61bb249-393a-4849-9232-cc1316143388)

Edit Mesh **only** works in the list mode, this would be the expected result without it :) 
Perhaps I should add some kind of warning or something in Modifier List. 

I will cloes the report, but thanks anyways!
