### ISSUE TITLE
Please submit to https://extensions.blender.org/

### ISSUE THREAD

**Issue by slrgt** [Dangry98/modifier_list-for-Blender-4.0#2]
Would be great to have this must have addon on the official extensions platform with auto update :)

**Comment by Dangry98** [comment]
This is planned :) 

But it will probably be released a few days or weeks after 4.2 is released due to lack of time for now.

**Comment by Dangry98** [comment]
@slrgt Done! https://extensions.blender.org/approval-queue/modifier-list-fork/

Closing once approvde :)

**Comment by Dangry98** [comment]
Modifier List is up now on the extension platform! 🥳 
https://extensions.blender.org/add-ons/modifier-list-fork/
Closing :)
