### ISSUE TITLE
Geometry node group is hidden

### ISSUE THREAD

**Issue by Rytelier** [Dangry98/modifier_list-for-Blender-4.0#7]
Geometry node group is hidden by default with no option to make it always show.
When adding new geometry node modifier, the `Show node group` setting is missing.

**Comment by Dangry98** [comment]
Please update the add-on to the lastest, and see if its fixed. I think this issue has been fixed already? If its similar to: https://github.com/Dangry98/modifier_list-for-Blender-4.0/issues/5

**Comment by Dangry98** [comment]
Hi, is this still a issue for you?

**Comment by Rytelier** [comment]
> Hi, is this still a issue for you?

Seems to fixed now
