### ISSUE TITLE
Missing boolean modifier options

### ISSUE THREAD

**Issue by tonpix** [Dangry98/modifier_list-for-Blender-4.0#8]
error in console
![blender_cUCEY6wrH6](https://github.com/user-attachments/assets/4b46aee6-2197-4020-9b66-5601f85f0eec)

used to have options like displaying booleans as wireframe
![blender_Ihq7Ar6y17](https://github.com/user-attachments/assets/f1f14316-87d6-4a4e-89c9-c49d47c3068d)

blender 4.2

**Comment by Dangry98** [comment]
Hi, unable to replicate the error, please send a test .blend file where it does not work. Or send more details on how to replicate the issue.

**Comment by tonpix** [comment]
Does this .blend file help? https://drive.google.com/file/d/1rWnFu5VfQ5luT2HvQH_qe4l98YasvhQ9/view?usp=sharing

I've noticed if I move windowsNomad collection to Scene Collection, boolean modifier fixes itself

**Comment by Dangry98** [comment]
Thanks! I also get the error now! I will take a look at it once I get time.

**Comment by Dangry98** [comment]
So it seems like it can not get acces to nested collections, works fine it its in scene.

**Comment by Dangry98** [comment]
Fixed: https://extensions.blender.org/add-ons/modifier-list-fork/manage/versions/#v192

**Comment by tonpix** [comment]
Awesome, thanks for quick fix 👍
