### ISSUE TITLE
The order of show render and show viewport reversed when displays as list mode, which is confusing, I think is a bug. 

### ISSUE THREAD

**Issue by silv3rarr0w** [Dangry98/modifier_list-for-Blender-4.0#9]
The order of show render and show viewport reversed when displays as list mode, which is confusing, I think is a bug. 
 ![image](https://github.com/user-attachments/assets/b4542dc8-4c64-4cd0-9d87-24a23eb1353a)
![image](https://github.com/user-attachments/assets/4c215aff-f2ca-4928-9162-3e4484122a92)

**Comment by silv3rarr0w** [comment]
oh I just found show in edit mode also revesed. Is it designed to be this? I think they should be consistent with blender's default setting.

**Comment by Dangry98** [comment]
Strange, never noticed that! Not sure why it was decided to be like this, but its not really a bug. 

Is there any resons why you would like to have the order revered, other than consistancy?

**Comment by silv3rarr0w** [comment]
> Strange, never noticed that! Not sure why it was decided to be in the reveresed order, but its not really a bug.
> 
> Is there any resons why you would like to have the order revered, other than consistancy?

I just think this arrangement broke people's operate habits.

**Comment by Dangry98** [comment]
Fixed in 1.9.7
